# Academic Assistant RAG Configuration
# Konfiguration für den akademischen Assistenten RAG

# Embedding Configuration
embedding:
  provider: "huggingface"
  huggingface:
    model_name: "intfloat/multilingual-e5-large"
    device: null  # Auto-detect
    max_length: 512
    batch_size: 32
    normalize_embeddings: true
    # German-specific settings
    language: "de"
    text_cleaning:
      remove_special_chars: true
      normalize_whitespace: true
      lowercase: false  # Keep German capitalization

# Vector Database Configuration
vectordb:
  provider: "chroma"
  chroma:
    persist_directory: "./data/chroma_db"
    collection_name: "akademische_dokumente"
    settings:
      anonymized_telemetry: false
      allow_reset: true
    # Collection metadata
    metadata:
      description: "Sammlung akademischer Dokumente und Forschungsarbeiten"
      language: "de"
      domain: "academic"
      version: "1.0"

# Document Processing Configuration
chunking:
  chunk_size: 512
  chunk_overlap: 50
  strategy: "recursive"
  # German-specific chunking
  language_specific:
    preserve_sentences: true
    respect_paragraphs: true
    handle_compound_words: true
  # Table detection for German content
  table_detection:
    enabled: true
    indicators:
      - "Tabelle"
      - "Tab."
      - "Spalte"
      - "Zeile"
      - "siehe Tabelle"
      - "in der Tabelle"
      - "─"
      - "│"

# Text Cleaning Configuration
text_cleaning:
  german:
    remove_umlauts: false
    normalize_umlauts: true
    handle_compound_words: true
    preserve_case: true
    remove_stopwords: false
    custom_stopwords:
      - "bzw."
      - "etc."
      - "usw."
      - "z.B."
      - "d.h."

# Retrieval Configuration
retrieval:
  top_k: 5
  score_threshold: 0.0
  min_similarity: 0.3
  # German content filtering
  filters:
    language: "de"
    content_type: ["text", "table", "figure"]
    academic_domain: ["economics", "finance", "business"]

# LLM Configuration
llm:
  provider: "ollama"
  model_name: "llama2"
  temperature: 0.1
  max_tokens: 512
  # German language settings
  language: "de"
  system_prompt: |
    Du bist ein hilfreicher akademischer Assistent, der auf Deutsch antwortet.
    Beantworte Fragen basierend auf den bereitgestellten Dokumenten.
    Verwende eine formelle, akademische Sprache.

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/academic_assistant.log"
  max_size: "10MB"
  backup_count: 5

# Data Processing Configuration
data:
  input_directory: "./data/raw"
  processed_directory: "./data/processed"
  output_directory: "./data/output"
  supported_formats:
    - "pdf"
    - "txt"
    - "docx"
  
# Performance Configuration
performance:
  batch_size: 100
  max_workers: 4
  cache_embeddings: true
  cache_directory: "./cache/embeddings"
  
# Testing Configuration
testing:
  test_data_directory: "./tests/data"
  mock_embeddings: true
  test_collection_name: "test_collection"
  cleanup_after_tests: true
